[workspace]
members = [
    # the CLI tool
    "blogrb",
    # libraries
    "blogrb-core", "brbnet-core", "brbnet-client",
    # containers
    "brbnet-api", "brbnet-build", "brbnet-cron", "brbnet-feed", "brbnet-serve", "brbnet-orb",
]
resolver = "2"
