[workspace]
members = [
    # containers
    "containers/api", "containers/site", "containers/gen", "containers/server", "containers/orb",
    # misc tooling/libraries
    "blogrb", "blogrb-core", "allocate",
]
resolver = "2"
